Repository FuelLabs/docs, pull requests merged in 2020-08, with the labels that each got.

#73 Update amount locked in DeFi
  src/v1.0.0/3. Concepts/0. Fundamentals/2. Security Analysis.md
Labels: documentation

#74 Live Code Example
  assets/images/discord.svg
  package-lock.json
  package.json
  public/favicon.png
  public/index.css
  public/index.html
  public/index.js
  src/v1.0.0/1. Introduction/1. Welcome.md
  src/v1.0.0/1. Introduction/3. Use Cases.md
  src/v1.0.0/2. Getting Started/0. Using the Wallet SDK.md
  src/v1.0.0/2. Getting Started/1. One-Click Example.md
  src/v1.0.0/2. SDK/1. Wallet.md
Labels: documentation, enhancement

#75 Better "Using the Wallet SDK" content
  package.json
  src/v1.0.0/1. Introduction/2. Benchmarks.md
  src/v1.0.0/2. Getting Started/0. Using the Wallet SDK.md
Labels: documentation, enhancement

#17 [WIP] Transaction eip712 serialization
  src/v1.0.0/3. Concepts/0. Fundamentals/5. Serialization.md
Labels: documentation, enhancement

#76 Transaction eip712 serialization - removing unused reference
  src/v1.0.0/3. Concepts/0. Fundamentals/5. Serialization.md
Labels: bug, documentation
